version: 2

updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "[Type] Build Tooling"
      - dependencies
      - php
    ignore:
      - dependency-name: phpunit/phpunit
        versions:
          - "> 7.5.20"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "[Type] Build Tooling"
      - dependencies
      - javascript
