name: Deploy plugin to WordPress.org

on:
  release:
    types: [published]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy updates
    runs-on: ubuntu-latest
    environment: wp.org plugin

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Build minified JavaScript and CSS and commit it just for the release
        run: |
          npm ci
          npm run build
          npm run prepare-release
          git config user.email "build@glotpress.blog"
          git config user.name "GlotPress Build"
          git add .
          git commit -m "Build" || true

      - name: WordPress.org plugin update
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.WORDPRESSORG_SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WORDPRESSORG_SVN_PASSWORD }}
          SLUG: glotpress
