name: Deploy plugin to WordPress.org

on:
  release:
    types: [published]
  pull_request:

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy updates
    runs-on: ubuntu-latest
    environment: wp.org plugin

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Build
        run: |
          npm install
          npm run build
          git config user.email "build@glotpress.blog"
          git config user.name "Glotpress Build"
          git add .
          git commit -m "Build"

      - name: WordPress.org plugin update
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          dry-run: true
        env:
          SVN_USERNAME: ${{ secrets.WORDPRESSORG_SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WORDPRESSORG_SVN_PASSWORD }}
          BUILD_DIR: build
          SLUG: glotpress
