name: Deploy plugin to WordPress.org

on:
  release:
    types: [published]

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy updates
    runs-on: ubuntu-latest
    environment: wp.org plugin

    steps:
      - name: Start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: WordPress.org

      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: WordPress.org plugin update
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: ${{ secrets.WORDPRESSORG_SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WORDPRESSORG_SVN_PASSWORD }}
          SLUG: glotpress

      - name: Update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
